# Generated by Django 3.2.7 on 2021-09-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumbersManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
